Models/ErrorViewModel.cs
namespace ProjectMgr.Models;

public class ErrorViewModel
{
    public string RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/Project.cs
#nullable disable
using System.ComponentModel.DataAnnotations;

namespace ProjectMgr.Models
{
    public class Project
    {
        public int Id { get; set; }
        [Required]
        public string ProjectName { get; set; }
        [MaxLength(255)]
        public string Description { get; set; }
        [Required]
        public string Owner { get; set; }
        [DataType(DataType.Date)]
        public DateTime StartedOn { get; set; }
        
        [DataType(DataType.Date)]
        public DateTime ClosedOn { get; set; }
        


    }
}

Models/Stakeholder.cs
using System.ComponentModel.DataAnnotations;

namespace ProjectMgr.Models
{
    public class Stakeholder
    {
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        public string Role { get; set; }
        public string Function { get; set; }
        public string Email { get; set; }
        public string ProjectTitle { get; set; }
        [DataType(DataType.Date)]
        public DateTime JoinedOn { get; set; }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using ProjectMgr.Models;

namespace ProjectMgr.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public List<Project> myProjects = new() {
        new Project {Id = 1, ProjectName="ProjectMgr", Description="Project Management tool for small projects/teams. Based on PMIs process groups.", Owner="Tinashe Chitakunye", StartedOn=DateTime.Parse("2021-12-13"), ClosedOn=DateTime.Parse("2022-02-01")},
        new Project {Id = 2, ProjectName="Abacustore", Description="Inventory Management System for small/medium stores.", Owner="Tinashe Chitakunye", StartedOn=DateTime.Parse("2022-02-03"), ClosedOn=DateTime.Parse("2022-02-26")},
        new Project {Id = 3, ProjectName="Kubhuya", Description="Small chat app for localised communications.", Owner="Anesu Chitakunye", StartedOn=DateTime.Parse("2022-01-13"), ClosedOn=DateTime.Parse("2022-04-01")},
        new Project {Id = 4, ProjectName="Bugly", Description="Bug tracking application for reporting, analysing, and resolving client tickets.", Owner="Tinashe Chitakunye", StartedOn=DateTime.Parse("2021-09-18"), ClosedOn=DateTime.Parse("2021-11-01")},
        new Project {Id = 5, ProjectName="Gadza", Description="News Recommendation System for subscribers based on their view choices.", Owner="Richard Dzingai", StartedOn=DateTime.Parse("2021-12-13"), ClosedOn=DateTime.Parse("2022-03-03")}
    };

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View(myProjects);
    }

    public IActionResult Privacy()
    {
        return View();
    }

    public IActionResult About()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/ProjectsController.cs
using Microsoft.AspNetCore.Mvc;
using ProjectMgr.Services;

namespace ProjectMgr.Controllers;


public class ProjectsController : Controller
{
    private readonly DummyProjectService _projectService;
    private readonly DummyStakeholderService _stakeholderService;

    public int projectId { get; set; } = default;

    public ProjectsController(DummyProjectService projectService, DummyStakeholderService stakeholderService)
    {
        _projectService = projectService;
        _stakeholderService = stakeholderService;
    }

    public IActionResult Index(int id)
    {
        var selectedProject = _projectService.GetProject(id);
        return View(selectedProject);
    }

    public IActionResult Initiation()
    {
        var allStakeholders = _stakeholderService.GetStakeholders();
        return View(allStakeholders);
    }
    public IActionResult Planning()
    {
        return View();
    }
    
    public IActionResult Executing()
    {
        return View();
    }
    public IActionResult Monitoring()
    {
        return View();
    }
    public IActionResult Closing()
    {
        return View();
    }

}

Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}

<div id="about" class="">
    <h3>About ProjectMgr</h3>
    <section class="about-section">
        <h4 class="about-heading">Introduction</h4>
        <p>ProjectMgr is a project management tool developer with ASP.NET 6 MVC, Entity Framework and hosted on heroku
            and developed by <a href="https://github.com/tinasche" target="_blank" style="color: darkcyan; text-decoration: none;">theasbyte</a>.</p>
        <p>The application is based on PMIs process groups and is specifically designed for use in small projects which are Initiation, Planning, Executing, Monitoring and Control, and Closing. Each of the phases are explained below so that you know how to [rperly use the app.</p>
    </section>
    <section class="about-section">
        <h4 class="about-heading">Initiation</h4>
        <p>This represents the first step in the project management phase. Its primary purpose is to compile documents necessary to present to project sponsors for approval and committment to the project. You want to get the buy-in so that there is an initial investment in the progresion of the project.</p>
        <p>Some assets of interest at this stage are:</p>
        <dl>
            <dt>Project Charter</dt>
            <dd>This document outlines a few elements such as: Objectives, Scope, Business Case, Time and Cost estimates, Milestones and Deliverables.</dd>
            <dt>Stakeholder Register</dt>
            <dd>Identify all the stakeholders that will be involved in the entire project. Include the fullnames, roles, contact information </dd>
        </dl>
    </section>
    <section class="about-section">
        <h4 class="about-heading">Planning</h4>
        <p>At this stage we look to financers to answer the following questions:</p>
        <ol>
            <li>What are we going to do?</li>
            <li>How are we going to do it?</li>
            <li>How to know when we are done?</li>
        </ol>
        <p>Some artefacts to consider at this stage include the following:</p>
        <dl>
            <dt>Project Plan</dt>
            <dd>This artefact will include the Requreiements Analysis document and Scope Baseline as a combination of all aspects of the planning phase.</dd>
            <dt>Requirements Analysis</dt>
            <dd>Hold a kick-off meeting with all the stakeholders/users involved to discuss the action points, features and requirements for the final deliverable. The more consensus is achieved the better. With the involvement of all the key players in the meeting, you can get a better, all-encompassing view of the expectations of the stakeholders. Produce a final Requirements Documents that is approved by the project team you represent (if one exists), stakeholders, and the users/clients.</dd>
            <dt>Scope Baseline</dt>
            <dd>This artefact is made up of the Scope Statement, Work Breakdown Structure (WBS) and WBS Dictionary</dd>
            <dt>Scope Statement</dt>
            <dd>Define the scope for the project and the associated boundaries. Once defined, work to protect this scope from scope creep on the scope boundaries. <em>Keep it as simple and straightforward as possible.</em> You can include any Risk Assumptions made.</dd>
            <dt>Work Breakdown Structure</dt>
            <dd>Decompose your final deliverable into specific <i>work packages</i>. Work packages must be as simple as possible to the extent that you confidently make cost and time estimates for each package. Tree like structure with ProjectName at the top, then label the packages per segment of the process. some aspects to include in the WBS are: 
            <ul>
                <li>Product Design</li>
                <li>Resources</li>
                <li>Communication Schedule</li>
                <li>Procurement Plan</li>
                <li>Quality Assurance Measures</li>
                <li>Change Management Plan</li>
            </ul>
            </dd>
            <dt>WBS Dictionary</dt>
            <dd>This section is used to define terms used in the Work Breakdown Structure for clarity.</dd>
        </dl> 
    </section>
    <section class="about-section">
        <h4 class="about-heading">Executing</h4>
        <p>Once the Planning Phase is concluded, worj can begin on the product. Follow the design made in the plan while tracking time, cost and quality bounds.</p>
    </section>
    <section class="about-section">
        <h4 class="about-heading">Monitoring and Control</h4>
        <p>Keep close watch on the constraints associated with the project: time, cost, quality and risk assessment must bedone to ensure you are still working withing the set limits. Communication channels should be kept open, with feedback given acording to the stipulated frequency. Conduct unit, integration and user acceptance tests for deliverables to ensure the quality checks are conducted in earnest.</p>
    </section>
    <section class="about-section">
        <h4 class="about-heading">Closing</h4>
        <p>At the end of the project and the final deliverable product is completed certain activites are expected to close off the project:</p>
        <dl>
            <dt>Handover</dt>
            <dd>Deliver the finished product to the client/stakeholders responsible to receive the output.</dd>
            <dt>Final Cost Records</dt>
            <dd>Account for all financial committments involved and return to responsible stakeholder.</dd>
            <dt>Releae reources</dt>
            <dd>Release any resources at the close of the project, whether it be personnel, materials, or other items claimed in the project development process.</dd>
            <dt>Lessons learnt</dt>
            <dd>Keep track of observations and lesons learnt during the project run. Maybe these can assist in future project to improve the process.</dd>
            <dt>Celebrate 🎆</dt>
            <dd>Make time to celebrate the completion of the project as you prepare for future endeavours.</dd>
        </dl>
        <p>There is provision to extract artefacts per phase or as a complete document for posterity. </p>
    </section>
</div>

Views/Home/Index.cshtml
@model List<ProjectMgr.Models.Project>
@{
    ViewData["Title"] = "Home Page";
}

<div id="top">
    <div class="p-5 mb-4 rounded-3" id="jumbo">
      <div class="container-fluid text-center py-5">
        <h1 class="display-5 fw-bold text-white" id="top-callout">Project Register</h1>
        <button class="btn btn-outline-secondary rounded-pill text-white mt-2">Create New Project</button>
      </div>
    </div>
</div>

<div class="row gap-3">
@foreach (Project projectItem in Model)
{
    <div class="card shadow-sm" style="width: 18rem;">
        <div class="card-body">
            <h5 class="card-title projectTitle">@projectItem.ProjectName</h5>
            <p class="card-text">@projectItem.Description</p>
            <a  class="card-link btn btn-dark" asp-controller="Projects" asp-action="Index" asp-route-id="@projectItem.Id">Explore</a>
        </div>
    </div>
}
</div>

Views/Projects/Closing.cshtml
@{
    ViewData["Title"] = "Closing";
}

<ul class="nav nav-tabs bg-dark">
  <li class="nav-item">
    <a class="nav-link text-white disabled" asp-action="Index">Introduction</a>
  </li>
  <li class="nav-item">
    <a class="nav-link text-white" asp-action="Initiation">Initiation</a>
  </li>
  <li class="nav-item">
    <a class="nav-link text-white" asp-action="Planning">Planning</a>
  </li>
  <li class="nav-item">
    <a class="nav-link text-white" asp-action="Executing">Executing</a>
  </li>
  <li class="nav-item">
    <a class="nav-link text-white" asp-action="Monitoring">Monitoring and Control</a>
  </li>
  <li class="nav-item">
    <a class="nav-link active" aria-current="page" asp-action="Closing">Closing</a>
  </li>
</ul>

<p>The Closing Page</p>

Views/Projects/Executing.cshtml
@{
    ViewData["Title"] = "Executing";
}

<ul class="nav nav-tabs bg-dark">
  <li class="nav-item">
    <a class="nav-link text-white disabled" asp-action="Index">Introduction</a>
  </li>
  <li class="nav-item">
    <a class="nav-link text-white" asp-action="Initiation">Initiation</a>
  </li>
  <li class="nav-item">
    <a class="nav-link text-white" asp-action="Planning">Planning</a>
  </li>
  <li class="nav-item">
    <a class="nav-link active" aria-current="page" asp-action="Executing">Executing</a>
  </li>
  <li class="nav-item">
    <a class="nav-link text-white" asp-action="Monitoring">Monitoring and Control</a>
  </li>
  <li class="nav-item">
    <a class="nav-link text-white" asp-action="Closing">Closing</a>
  </li>
</ul>

<p>The Executing Page</p>

Views/Projects/Index.cshtml
@model ProjectMgr.Models.Project
@{
    ViewData["Title"] = "Overview";
}

<ul class="nav nav-tabs bg-dark">
  <li class="nav-item">
    <a class="nav-link active" aria-current="page" asp-action="Index">Introduction</a>
  </li>
  <li class="nav-item">
    <a class="nav-link text-white" asp-action="Initiation">Initiation</a>
  </li>
  <li class="nav-item">
    <a class="nav-link text-white" asp-action="Planning">Planning</a>
  </li>
  <li class="nav-item">
    <a class="nav-link text-white" asp-action="Executing">Executing</a>
  </li>
  <li class="nav-item">
    <a class="nav-link text-white" asp-action="Monitoring">Monitoring and Control</a>
  </li>
  <li class="nav-item">
    <a class="nav-link text-white" asp-action="Closing">Closing</a>
  </li>
</ul>

<p>The Intro Page</p>
<p>This project is <b>@Model.ProjectName</b></p>
<button class="btn btn-outline-secondary">Press Me</button>

Views/Projects/Initiation.cshtml
@model IEnumerable<ProjectMgr.Models.Stakeholder>
@{
    ViewData["Title"] = "Initiation";
}

<ul class="nav nav-tabs bg-dark">
  <li class="nav-item">
    <a class="nav-link text-white disabled" asp-action="Index">Introduction</a>
  </li>
  <li class="nav-item">
    <a class="nav-link active" aria-current="page" asp-action="Initiation">Initiation</a>
  </li>
  <li class="nav-item">
    <a class="nav-link text-white" asp-action="Planning">Planning</a>
  </li>
  <li class="nav-item">
    <a class="nav-link text-white" asp-action="Executing">Executing</a>
  </li>
  <li class="nav-item">
    <a class="nav-link text-white" asp-action="Monitoring">Monitoring and Control</a>
  </li>
  <li class="nav-item">
    <a class="nav-link text-white" asp-action="Closing">Closing</a>
  </li>
</ul>

@* Project Charter and Stakeholder Register sections
Project Charter to include: Objectives, Scope, Business case, Time and Cost estimates, Milestones, and Major deliverables.
Stakeholder Register to include a table? of stakeholders with their information *@

<section class="pt-2">
  <h4 class="projectTitle">Project Charter</h4>
  <h5>Objectives</h5>
  <h5>Scope</h5>
  <h5>Business Case</h5>
  <h5>Time and cost Estimates</h5>
  <h5>Milestones</h5>
  <h5>Major Deliverables</h5>
</section>
<section class="pt-2">
  <h4 class="projectTitle">Stakeholder Register</h4>
  <table class="table table-hover">
    <thead class="bg-dark text-light">
      <th>@Html.DisplayNameFor(model => model.Name)</th>
      <th>@Html.DisplayNameFor(model => model.Role)</th>
      <th>@Html.DisplayNameFor(model => model.Function)</th>
      <th>@Html.DisplayNameFor(model => model.Email)</th>
      <th>Actions</th>
    </thead>
    <tbody>
      @foreach (Stakeholder stakeholder in Model)
      {
      <tr>
        <td>@stakeholder.Name</td>
        <td>@stakeholder.Role</td>
        <td>@stakeholder.Function</td>
        <td>@stakeholder.Email</td>
        @* RESEARCH: Separate controller for managing stakeholders? *@
        <td>
          <a asp-controller="Stakeholders" asp-action="Edit" asp-route-id="@stakeholder.Id" style="text-decoration: none;">Edit</a> |
          <a asp-controller="Stakeholders" asp-action="Details" asp-route-id="@stakeholder.Id" style="text-decoration: none;">Details</a> |
          <a asp-controller="Stakeholders" asp-action="Details" asp-route-id="@stakeholder.Id" style="text-decoration: none;">Delete</a>
        </td>
      </tr>
      }
    </tbody>
  </table>
</section>
      

Views/Projects/Monitoring.cshtml
@{
    ViewData["Title"] = "Monitoring";
}

<ul class="nav nav-tabs bg-dark">
  <li class="nav-item">
    <a class="nav-link text-white disabled" asp-action="Index">Introduction</a>
  </li>
  <li class="nav-item">
    <a class="nav-link text-white" asp-action="Initiation">Initiation</a>
  </li>
  <li class="nav-item">
    <a class="nav-link text-white" asp-action="Planning">Planning</a>
  </li>
  <li class="nav-item">
    <a class="nav-link text-white" asp-action="Executing">Executing</a>
  </li>
  <li class="nav-item">
    <a class="nav-link active" aria-current="page" asp-action="Monitoring">Monitoring and Control</a>
  </li>
  <li class="nav-item">
    <a class="nav-link text-white" asp-action="Closing">Closing</a>
  </li>
</ul>

<p>The Monitoring Page</p>

Views/Projects/Planning.cshtml
@{
    ViewData["Title"] = "Planning";
}

<ul class="nav nav-tabs bg-dark">
  <li class="nav-item">
    <a class="nav-link text-white disabled" asp-action="Index">Introduction</a>
  </li>
  <li class="nav-item">
    <a class="nav-link text-white" asp-action="Initiation">Initiation</a>
  </li>
  <li class="nav-item">
    <a class="nav-link active" aria-current="page" asp-action="Planning">Planning</a>
  </li>
  <li class="nav-item">
    <a class="nav-link text-white" asp-action="Executing">Executing</a>
  </li>
  <li class="nav-item">
    <a class="nav-link text-white" asp-action="Monitoring">Monitoring and Control</a>
  </li>
  <li class="nav-item">
    <a class="nav-link text-white" asp-action="Closing">Closing</a>
  </li>
</ul>

<p>The Planning Page</p>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProjectMgr</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProjectMgr.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light box-shadow mb-3 sticky-top fixed-top" id="laynav">
            <div class="container-fluid">
                <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">ProjectMgr</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white disabled" asp-area="" asp-controller="Projects" asp-action="Index">Projects</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="About">How it works</a>
                        </li>
                    </ul>
                </div>
                
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-dark">
        <div class="container">
            &copy; @DateTime.Now.Year - ProjectMgr - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>